config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'

  resources :articles

  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	validates :title, presence: true, length: { minimum: 5, maximum: 35 }
	validates :description, presence: true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles, dependent: :destroy
	before_save { self.email = email.downcase }
	validates :username, presence: true,
				uniqueness: { case_sensitive: false },
				length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
				uniqueness: { case_sensitive: false },
				format: { with: VALID_EMAIL_REGEX }
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?, :only_for_guess

  def current_user
 	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end

  def require_guess
		if current_user
			flash[:warning] = "You have logged in to your profile"
			redirect_to user_path(current_user)
		end
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
		@article = Article.new
	end

	def edit
	end

	def create
		@article 		= Article.new(article_params)
		@article.user 	= current_user
		if @article.save
			flash[:success] = "Article was successfully created"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article was successfully updated"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:success] = "Article was successfully deleted"
		redirect_to articles_path
	end

	private
	def set_article
		@article = Article.find(params[:id])
	end

	def article_params
		params.require(:article).permit(:title, :description)
	end

	def require_same_user
		if current_user != @article.user and !current_user.admin?
			flash[:danger] = "You have to be article author to perform this action"
			redirect_to articles_path
		end
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end

	def about
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :require_guess, only: [:new, :create]

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Welcome back #{user.username}"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "Something wrong with your login information"
			render 'new'
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_guess, only: [:new, :create]
	before_action :require_admin, only: [:destroy]

	def index
		@users = User.paginate(page: params[:page], per_page: 3)
	end

	def new
		@user = User.new
		render 'new'
	end

	def create

		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the Alpha Blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end

	end

	def edit
	end

	def update
		if(@user.update(user_params))
			flash[:success] = "Account updated successfully"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:success] = "User and his articles have been deleted"
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can't edit other profile"
			redirect_to root_path
		end
	end

	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only admin can perform this action"
			redirect_to users_path
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user, options = { size: 80 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{gravatar_size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end
end

app/views/articles/_articles.html.erb
<div class="clearfix"></div>
<% obj.each do |article| %>
	<div class="well well-lg">
		<div class="article-title">
			<h3><%= link_to article.title, article_path(article), class: "article-link" %></h3>
		</div>
		<div class="article-body">
			<p>
				<%= truncate(article.description, length: 100) %>
			</p>
			<div class="article-meta">
				<small>Created by <strong><%= article.user.username if article.user  %></strong> on <%= time_ago_in_words(article.created_at) %> ago. Last updated on <%= time_ago_in_words(article.updated_at) %> ago</small>
			</div>
		</div>
		<% if logged_in? && (current_user == article.user || current_user.admin? ) %>
		<div class="article-action">
			<%= link_to "Edit", edit_article_path(article), class: "btn btn-sm btn-info" %>
			<%= link_to "Delete", article_path(article), method: :delete, data: {confirm: "Are you sure? "}, class: "btn btn-sm btn-danger" %>
		</div>
		<% end %>
	</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>
<div class="well well-lg">
	<%= form_for @article, html: { class: "" } do |f| %>
		<div class="form-group">
			<%= f.label :title, class: "control-label" %>
			<%= f.text_field :title, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.label :description, class: "control-label" %>
			<%= f.text_area :description, class: "form-control" %>
		</div>
		<div class="form-group">
			<%= f.submit "Save", class: 'btn btn-lg btn-primary' %>
		</div>
	<% end %>
</div>
<%= link_to "Back to Articles List", articles_path, class: "btn btn-sm btn-warning" %>

app/views/articles/edit.html.erb
<h1>Editing existing article</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="pull-left">Listing all articles</h1>
<%= link_to "Create new article", new_article_path, class: "btn btn-primary pull-right main-btn"  %>
<div class="clearfix"></div>
<div class="text-center">
	<%= will_paginate %>
</div>
<%= render 'articles', obj: @articles %>
<div class="text-center">
	<%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 class="text-center">Create an article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<div class="well well-lg">
	<div class="article-title">
		<h3><%= @article.title %></h3>
	</div>
	<div class="article-body">
		<p>
			<%= @article.description %>
		</p>
	</div>
</div>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Author</h3>
  </div>
  <div class="panel-body">
    <div class="row">
		<div class="col-md-2 text-center">
			<%= link_to gravatar_for(@article.user), user_path(@article.user) %>
		</div>
		<div class="col-md-10 user-details">
			<h3><%= link_to @article.user.username, user_path(@article.user) %></h3>
			<p><%= pluralize(@article.user.articles.count, "article") if @article.user.articles %></p>
		</div>
	</div>
  </div>
</div>


<% if logged_in? && (current_user == @article.user || current_user.admin? ) %>
<%= link_to "Edit this article", edit_article_path(@article), class: "btn btn-sm btn-info" %>
<%= link_to "Back to Articles List", articles_path, class: "btn btn-sm btn-warning" %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
<div class="alert alert-<%= "#{name}" %> alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
  <%= msg %>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "Users", users_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Action <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New article", new_article_path %></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in?  %>
        <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">My Profile <%= "Admin" if current_user.admin? %><span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Edit my profile", edit_user_path(current_user) %></li>
            <li><%= link_to "View my profile", user_path(current_user) %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to 'Login', login_path %></li>
        <li><%= link_to 'Sign Up', signup_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
    	<%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the about page</h1>
<%= link_to "Home", root_path %>

app/views/pages/home.html.erb
<div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>...</p>
  <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a></p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="panel panel-danger">
	<div class="panel-heading"><%= pluralize(obj.errors.count, "error") %> occured</div>
	<div class="panel-body">
		<ul>
			<% obj.errors.full_messages.each do |msg| %>	
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="well well-lg">
	<%= form_for @user, html: { class: "", role: "form" } do |f| %>
		<div class="form-group">
			<%= f.label :username, class: "control-label" %>
			<%= f.text_field :username, class: "form-control", placeholder: "Enter your username" %>
		</div>
		<div class="form-group">
			<%= f.label :email, class: "control-label" %>
			<%= f.email_field :email, class: "form-control", placeholder: "Enter your email" %>
		</div>
		<div class="form-group">
			<%= f.label :password, class: "control-label" %>
			<%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
		</div>
		<div class="form-group">
			<%= f.submit(@user.new_record? ? "Sign Up" : "Update", class: 'btn btn-lg btn-primary') %>
		</div>
	<% end %>
</div>

app/views/users/edit.html.erb
<h1 class="text-center">Edit your account</h1>
<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center">All users list</h1>
<div class="text-center">
	<%= will_paginate %>
</div>
<% @users.each do |user| %>
	<div class="well well-lg">
		<div class="row">
			<div class="col-md-3 text-center">
				<%= link_to gravatar_for(user), user_path(user) %>
			</div>
			<div class="col-md-9 user-details">
				<h3><%= link_to user.username, user_path(user) %></h3>
				<p><%= pluralize(user.articles.count, "article") if user.articles %></p>
				<% if logged_in? and current_user.admin? %>
					<%= link_to "Delete user", user_path(user), method: :delete, data: {confirm: "Are you sure to delete this user ? "}, class: "btn btn-danger" %>
				<% end %>
			</div>
		</div>
	</div>
<% end %>
<div class="text-center">
	<%= will_paginate %>
</div>

app/views/users/new.html.erb
<h1 class="text-center">Signup for Alpha Blog</h1>
<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center">Welcome to <%= @user.username %>'s page</h1>
<div class="row">
	<div class="col-md-4 col-md-offset-4 text-center">
		<%= gravatar_for @user, size: 150 %>
	</div>
</div>
<h4 class="text-center"><%= @user.username %>'s articles</h4>
<div class="text-center">
	<%= will_paginate @user_articles %>
</div>
<%= render 'articles/articles', obj: @user_articles %>
<div class="text-center">
	<%= will_paginate @user_articles %>
</div>